name: yyy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    name: Publish release of font files
    runs-on: ubuntu-latest
    steps:
      - name: Create foo file
        run: |
          mkdir cascadios
          > cascadios/foo.txt
          
      - name: Get tag name from date
        id: tag_name
        run: echo "::set-output name=date::$(date +'%y%m.%d')"

      - name: Zip font files
        run: |
          cd cascadios
          zip ../cascadios-${{ steps.tag_name.outputs.date }}.zip *
          cd ..

      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          github_token: ${{ github.token }}
          custom_tag: ${{ steps.tag_name.outputs.date }}
